"Filed out from Dolphin Smalltalk 7"!

Axiom subclass: #Terminal
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Terminal guid: (GUID fromString: '{51D4E92C-1E17-40B5-A4BF-B190FC369EDE}')!
Terminal comment: ''!
!Terminal categoriesForClass!Kernel-Objects! !
!Terminal methodsFor!

isTerminal
	^true! !
!Terminal categoriesFor: #isTerminal!private! !

